name: Upload ZIP to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run s3-zip-upload
        uses: NotCoffee418/s3-zip-upload@v1.4
        env:
          role-to-assume: arn:aws:iam::017820695651:role/Github-role
          role-session-name: Github-role
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_REGION: ap-south-1
          SOURCE_MODE: ZIP
          SOURCE_PATH: /mnt/c/Users/karnapa/desktop/s3git
          DEST_FILE: action.zip
