name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::017820695651:role/Github-role
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Zip files
        run: zip -r my-files.zip .

      - name: Start SSM session
        id: start-session
        run: |
          aws ssm start-session --target ${{ secrets.INSTANCE_ID }} --document-name AWS-StartPortForwardingSessionToRemoteHost --parameters '{"portNumber":["22"],"localPortNumber":["2222"]}'

      - name: Upload to S3
        run: |
          aws s3 cp my-files.zip s3://${{ secrets.S3_BUCKET_NAME }}/my-files.zip

permissions:
  id-token: write
  contents: read
