name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials for S3 Access (Optional)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::017820695651:role/Github-role  # Optional - Only if needed for actions before upload
          audience: sts.amazonaws.com

      - name: Zip files
        run: zip -r my-files.zip .

      - name: Upload to S3 (Using IAM Role on EC2 Instance)
        uses: aws-actions/aws-cli@v3
        with:
          aws-command: s3 cp
          args: my-files.zip s3://${{ secrets.S3_BUCKET_NAME }}/my-files.zip
          region: ${{ secrets.AWS_REGION }}

permissions:
  id-token: write
  contents: read
